# fly.toml app configuration file generated for devhub-cache-api-rs-2 on 2025-03-20T10:30:36-05:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#
# org: devhub-128
app = 'devhub-cache-api-rs-2'
primary_region = 'ams'

[build]

[env]
CONTRACT = 'devhub.near'
ROCKET_PROFILE = 'release'

[http_service]
internal_port = 8080
force_https = true
auto_stop_machines = 'stop'
auto_start_machines = true
min_machines_running = 1
processes = ['app']

[[vm]]
memory = '1gb'
cpu_kind = 'shared'
cpus = 1
