# fly.toml app configuration file generated for testing-indexer-2 on 2025-03-20T10:45:30-05:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'testing-indexer-2'
primary_region = 'ams'

[build]

[env]
  CONTRACT = 'testing-indexer.near'
  ROCKET_PROFILE = 'release'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 1
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
