# fly.toml app configuration file generated for devhub-cache-api-rs on 2024-11-06T08:54:33+07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'devhub-cache-api-rs'
primary_region = 'ams'

[build]

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
