name: Rust CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Rust toolchain
        uses: dsherret/rust-toolchain-file@v1

      - name: Install dependencies
        run: sudo apt-get update -y && sudo apt-get install -y libssl-dev ca-certificates libudev-dev libusb-1.0-0-dev pkg-config libudev-dev build-essential

      - name: Set up PostgreSQL database
        run: |
          sudo service postgresql start
          sudo su - postgres -c "
            psql -c \"CREATE DATABASE devhub_cache_api_rs\"
            psql -c \"CREATE ROLE devhub_cache_api_rs WITH LOGIN PASSWORD 'password';\"
            psql -c \"ALTER ROLE devhub_cache_api_rs CREATEDB;\"
            psql -c \"GRANT ALL PRIVILEGES ON DATABASE devhub_cache_api_rs TO devhub_cache_api_rs;\"
          "
      - name: Install SQlx
        run: cargo install sqlx-cli

      - name: Create database tables
        run: cargo sqlx database create

      - name: Build the project
        run: cargo build --verbose
        env:
          SQLX_OFFLINE: true

      - name: Run tests
        env:
          CONTRACT: devhub.near
          DATABASE_URL: postgres://devhub_cache_api_rs:password@127.0.0.1:5432/devhub_cache_api_rs
        run: cargo test --verbose

      - name: Run clippy
        run: cargo clippy -- -D warnings

      - name: Install cargo audit
        run: |
          cargo install cargo-audit

      - name: Run cargo audit
        run: cargo audit
